### ISSUE TITLE
Editing passwords doesn't work (via saved-password-editor)

### ISSUE THREAD

**Issue by infinity0** [swick/moz-gnome-keyring-integration#25] opened 2015-05-30 19:49 UTC
Using the [saved-password-editor](https://addons.mozilla.org/en-US/firefox/addon/saved-password-editor/) extension together with this extension allows for easier testing. Unfortunately, editing an existing entry doesn't work:

~~~~
Got an error:
  [JavaScript Error: "propEnum is undefined" {file: "jar:file:///home/infinity0/.mozilla/firefox/xxx.testing/extensions/gnome-keyring-integration@sebastianwick.net.xpi!/components/loginManagerStorage.js" line: 127}]'[JavaScript Error: "propEnum is undefined" {file: "jar:file:///home/infinity0/.mozilla/firefox/xxx.testing/extensions/gnome-keyring-integration@sebastianwick.net.xpi!/components/loginManagerStorage.js" line: 127}]' when calling method: [nsILoginManagerStorage::modifyLogin]
Did you try to create a duplicate login entry?
~~~~

**Comment by infinity0** [comment] 2015-05-30 19:58
However, updating a password normally (by manually changing the autocompleted password, then submitting the form) does work, and shows up both in seahorse and saved-password-editor.

**Comment by swick** [comment] 2015-05-30 21:22
Which version are you using? 0.8 doesn't throw an error for me - it doesn't work correctly, though (i.e. it creates a duplicate of the original with the changes applied).

Not storing an ID in the entries makes it really hard to select the correct entry.

**Comment by infinity0** [comment] 2015-05-30 22:01
I'm using 0.9 and saved-password-editor 2.9.1. Adding `this.log(newLoginData)` after `newLoginData instanceof Components.interfaces.nsIPropertyBag`, we see that firefox itself gives a `[xpconnect wrapped nsIPropertyBag]` to `modifyLogin`, but saved-password-editor gives a `[xpconnect wrapped nsISupports]` that still somehow passes the instanceof check. Will investigate further...

**Comment by infinity0** [comment] 2015-05-30 22:15
OK, I fixed it, will send a patch soon.

**Closed** 2015-07-01 17:12 UTC
